{
 "title": "MiTemp 2",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Mi Temperatur in C°",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "temp_celsius", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "Mi Luftfeuchtigkeint in %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "humidity_pct", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "Mi Batteriespannung in V",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "battery_voltage", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "OpenWeather",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "openweathermap_temperature_celsius",
     "legendFormat": "{{location}} Temperatur in C°"
    },
    {
     "expr": "openweathermap_humidity_percent",
     "legendFormat": "{{location}} Luftfeuchtigkeit in %"
    }
   ]
  }
 ]
}