scrape_configs:
  - job_name: prometheus-gateway
    static_configs:
      - targets: ["prometheus-gateway:9091"]
  - job_name: openweather-exporter
    static_configs:
      - targets: ["openweather-exporter:2112"]
